---
# Installs powerline shell system wide on Ubuntu

- hosts: all
  remote_user: ubuntu

  tasks:
  - name: Install git
    apt: pkg=git state=latest
    sudo: yes

  - name: Git clone milkbikis powerline
    git: repo=https://github.com/milkbikis/powerline-shell dest=/tmp/milkbikis

  - name: Copy config file, use defaults
    shell: "cp /tmp/milkbikis/config.py.dist /tmp/milkbikis/config.py"

  - name: Execute install
    shell: ./install.py
    args:
      chdir: /tmp/milkbikis

  - name: Copy script
    shell: "cp /tmp/milkbikis/powerline-shell.py /usr/local/bin/powerline-shell.py"
    sudo: yes

  - name: Set exec permissions to shell script
    shell: "chmod 755 /usr/local/bin/powerline-shell.py"
    sudo: yes

  - name: Set global config to use powerline
    lineinfile: dest=/etc/bash.bashrc line='function _update_ps1() {\n  export PS1="$(/usr/local/bin/powerline-shell.py $? 2> /dev/null)"\n}\n\nexport PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"'
    sudo: yes

