---
# Installs powerline shell system wide on Ubuntu

- hosts: all
  remote_user: ubuntu

  tasks:
  - name: Install python-pip
    apt: pkg=python-pip state=latest
    sudo: yes

  - name: Install git
    apt: pkg=git state=latest
    sudo: yes

  - name: Install powerline
    shell: pip install git+git://github.com/Lokaltog/powerline
    sudo: yes

#  - name: Download fonts
#    get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf dest=/tmp/

#  - name: Download fonts 2
#    get_url: url=https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf dest=/tmp/

#  - name: create fonts directory
#    file: state=directory path=/usr/share/fonts
#    sudo: yes

#  - name: copy fonts
#    copy: src=/tmp/PowerlineSymbols.otf dest=/usr/share/fonts/
#    sudo: yes

  - name: Add powerline to global bashrc
    lineinfile: dest=/etc/bash.bashrc line="if [ -f /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh ]; then source /usr/local/lib/python2.7/dist-packages/powerline/bindings/bash/powerline.sh; fi"
    sudo: yes


